### ISSUE TITLE
Games written in Racket

### ISSUE THREAD

**Issue by soegaard** [avelino/awesome-racket#8]
https://github.com/racket/games

**Comment by avelino** [comment]
@soegaard send PR pls

**Comment by spdegabrielle** [comment]
@soegaard @avelino
Done see #9

**Comment by spdegabrielle** [comment]
@soegaard updated with your link
Thank you for contributing to awesome-Racket 😀

**Comment by spdegabrielle** [comment]
@avelino please close this issue
